mqtt:
  enabled: false
auth:
  reset_admin_password: false
detectors:
  ov:
    type: openvino
    device: GPU
  ov_2:
    type: openvino
    device: GPU
  # ov_3:
  #   type: openvino
  #   device: GPU
  # ov_4:
  #   type: openvino
  #   device: GPU


model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  path: /openvino-model/ssdlite_mobilenet_v2.xml
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

cameras:
  camera_1:
    enabled: true
    ffmpeg:
      hwaccel_args: preset-intel-qsv-h264
      inputs:
        - path: 
            rtsp://user:pw@ip/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        - path: rtsp://user:pw@ip
          roles:
            - record
detect:
  enabled: true # <---- disable detection until you have a working camera feed
  width: 960
  height: 540
  fps: 10
  stationary:
    interval: 50
    threshold: 50
objects:
  track:
    - person
    - car

record:
  enabled: true
  retain:
    days: 3
    mode: motion
  alerts:
    retain:
      days: 5
      mode: motion
  detections:
    retain:
      days: 5
      mode: motion
snapshots:
  enabled: true
motion:
  enabled: true
  threshold: 200